### ISSUE TITLE
Allow easily entering a bash shell inside a container

### ISSUE THREAD

**Issue by orf** [orf/django-docker-box#9]
Right now we define an `ENTRYPOINT` inside the docker-compose definitions that points to `python runtests.py`. This makes it convenient to run tests (`docker-compose run sqlite [TEST NAME]`), but entering a bash shell to debug something is hard.

We should be able to support something like `docker-compose run sqlite bash` and have it open a bash shell.

**Comment by apollo13** [comment]
I do not think entering bash is that hard:
```
docker-compose run --rm --entrypoint bash sqlite
```
Given your example above it is just one word (`--entrypoint`) more. Not sure it's worth to special case this.

**Comment by orf** [comment]
Good point! I've added documentation for this instead 👍
